name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Pasul 1: Instalează dependențele (creează node_modules)
      - name: Install dependencies
        run: npm install

      # Pasul 2: Corectează permisiunile pentru react-scripts DUPĂ npm install
      - name: Fix react-scripts permissions
        run: chmod +x node_modules/.bin/react-scripts

      # Pasul 3: Build și Deploy cu NODE_OPTIONS setat direct în env-ul pasului
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          NODE_OPTIONS: "--openssl-legacy-provider" # Setează NODE_OPTIONS aici
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_DUNE_02CBB2810 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Folosit pentru integrări GitHub (ex: comentarii PR)
          action: "upload"
          ###### Configurații Repository/Build ######
          app_location: "/" # Calea către codul sursă al aplicației
          api_location: "" # Calea către codul sursă al API-ului - opțional
          output_location: "build" # Directorul cu conținutul aplicației compilate - opțional
          ###### Sfârșitul Configurațiilor Repository/Build ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_DUNE_02CBB2810 }}
          action: "close"
